/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.appmdi.formularios;

import com.mycompany.appmdi.Empregado;
import com.mycompany.appmdi.EmpregadoCLT;
import com.mycompany.appmdi.EmpregadoHorista;
import com.mycompany.appmdi.FormMain;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luizh
 */
public class Empregados extends javax.swing.JInternalFrame {

    /**
     * Creates new form Empregados
     */
    public Empregados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jRCLT = new javax.swing.JRadioButton();
        jRHorista = new javax.swing.JRadioButton();
        jRTodos = new javax.swing.JRadioButton();
        jbListar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Cadastrar Empregados");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Endereço", "CPF", "Salario Bruto", "Numero de Horas", "Valor da Hora"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        buttonGroup1.add(jRCLT);
        jRCLT.setText("CLT");
        jRCLT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRCLTActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRHorista);
        jRHorista.setText("Horista");
        jRHorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRHoristaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRTodos);
        jRTodos.setSelected(true);
        jRTodos.setText("Todos");
        jRTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRTodosActionPerformed(evt);
            }
        });

        jbListar.setText("Listar");
        jbListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jRCLT)
                .addGap(32, 32, 32)
                .addComponent(jRHorista)
                .addGap(26, 26, 26)
                .addComponent(jRTodos)
                .addGap(36, 36, 36)
                .addComponent(jbListar, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRCLT)
                    .addComponent(jRHorista)
                    .addComponent(jRTodos)
                    .addComponent(jbListar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRHoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRHoristaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRHoristaActionPerformed

    private void jRCLTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRCLTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRCLTActionPerformed

    private void jRTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRTodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRTodosActionPerformed

    private void jbListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbListarActionPerformed
        
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        FormMain form = new FormMain();
        
        Empregado empregados[] = form.getEmpregados();
        Integer index = form.getIndex();
        
        model.setNumRows(0);
        
        for (int count = 0; count < index; count++){
            
 
            if ((jRCLT.isSelected() || jRTodos.isSelected()) && empregados[count] instanceof EmpregadoCLT) {
                EmpregadoCLT temp = (EmpregadoCLT)empregados[count];
                
                model.addRow(new Object[]{
                    temp.getNome(),
                    temp.getEndereco(),
                    temp.getCpf(), 
                    temp.getsBrutoCLT()
                    });
            }
           
            if ((jRHorista.isSelected() || jRTodos.isSelected()) && empregados[count] instanceof EmpregadoHorista) {
                EmpregadoHorista temp = (EmpregadoHorista)empregados[count];
                  
                model.addRow(new Object[]{
                    temp.getNome(),
                    temp.getEndereco(),
                    temp.getCpf(), 
                    "",
                    temp.getnHoras(),
                    temp.getPrecoH()
                    });
            }
        }
         
    }//GEN-LAST:event_jbListarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jRCLT;
    private javax.swing.JRadioButton jRHorista;
    private javax.swing.JRadioButton jRTodos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbListar;
    // End of variables declaration//GEN-END:variables
}
