/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.appmdi.formularios;

import com.mycompany.appmdi.FormMain;
import javax.swing.JOptionPane;

/**
 *
 * @author luizh
 */
public class Horista extends javax.swing.JInternalFrame {

    /**
     * Creates new form Horista
     */
    public Horista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlNumeroHoras = new javax.swing.JLabel();
        jtNomeHorista = new javax.swing.JTextField();
        jtEnderecoHorista = new javax.swing.JTextField();
        jtCPFHorista = new javax.swing.JTextField();
        jtNumeroDeHoras = new javax.swing.JTextField();
        jbSalvarHorista = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtPrecoDasHoras = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);
        setTitle("Cadastro Horista");

        jLabel1.setText("Nome");

        jLabel2.setText("Endereço");

        jLabel3.setText("CPF");

        jlNumeroHoras.setText("Numero de Horas");

        jtEnderecoHorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtEnderecoHoristaActionPerformed(evt);
            }
        });

        jtCPFHorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCPFHoristaActionPerformed(evt);
            }
        });

        jtNumeroDeHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNumeroDeHorasActionPerformed(evt);
            }
        });

        jbSalvarHorista.setText("Salvar");
        jbSalvarHorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarHoristaActionPerformed(evt);
            }
        });

        jLabel4.setText("Preço das Horas");

        jtPrecoDasHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPrecoDasHorasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtNomeHorista)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlNumeroHoras)
                                .addGap(49, 49, 49))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtCPFHorista, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(jtEnderecoHorista))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtPrecoDasHoras, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                    .addComponent(jtNumeroDeHoras))))
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(73, 73, 73))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jbSalvarHorista)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtNomeHorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtEnderecoHorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtPrecoDasHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtCPFHorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtNumeroDeHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(jbSalvarHorista)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlNumeroHoras)
                        .addGap(109, 109, 109))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtEnderecoHoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtEnderecoHoristaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtEnderecoHoristaActionPerformed

    private void jtNumeroDeHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNumeroDeHorasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNumeroDeHorasActionPerformed

    private void jbSalvarHoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarHoristaActionPerformed
        FormMain form = new FormMain();
        
        String nome;
        String cpf;
        String endereco;
        int nHoras;
        Double precoH;
        
        nome = jtNomeHorista.getText();
        cpf = jtCPFHorista.getText();
        endereco = jtEnderecoHorista.getText();
        nHoras = Integer.parseInt(jtNumeroDeHoras.getText());
        precoH = Double.parseDouble(jtPrecoDasHoras.getText());
        
        form.inserirHorista(nome, cpf, endereco, nHoras, precoH);
        
        JOptionPane.showMessageDialog(rootPane, "Registro salvo!");
        
        jtNomeHorista.setText("");
        jtCPFHorista.setText("");
        jtEnderecoHorista.setText("");
        jtNumeroDeHoras.setText("");
        jtPrecoDasHoras.setText("");
    }//GEN-LAST:event_jbSalvarHoristaActionPerformed

    private void jtPrecoDasHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPrecoDasHorasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPrecoDasHorasActionPerformed

    private void jtCPFHoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCPFHoristaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCPFHoristaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbSalvarHorista;
    private javax.swing.JLabel jlNumeroHoras;
    private javax.swing.JTextField jtCPFHorista;
    private javax.swing.JTextField jtEnderecoHorista;
    private javax.swing.JTextField jtNomeHorista;
    private javax.swing.JTextField jtNumeroDeHoras;
    private javax.swing.JTextField jtPrecoDasHoras;
    // End of variables declaration//GEN-END:variables
}
