/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.appguitxt;

import javax.swing.JOptionPane;

/**
 *
 * @author luizh
 */
public class FormMain extends javax.swing.JFrame {
    CreateTextFile arquivo = new CreateTextFile();
    /**
     * Creates new form FormMain
     */
    public FormMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbAbrirArquivo = new javax.swing.JButton();
        jbFecharArquivos = new javax.swing.JButton();
        jtNumeroConta = new javax.swing.JTextField();
        jtPrimeiroNome = new javax.swing.JTextField();
        jtBalance = new javax.swing.JTextField();
        jtSobrenome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlEstadoArquivo = new javax.swing.JLabel();
        jbEnviarDados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbAbrirArquivo.setText("Abrir Arquivo");
        jbAbrirArquivo.setName("jbAbrirArquivo"); // NOI18N
        jbAbrirArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAbrirArquivoActionPerformed(evt);
            }
        });

        jbFecharArquivos.setText("Fechar Arquivos");
        jbFecharArquivos.setName("jbFecharArquivos"); // NOI18N
        jbFecharArquivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFecharArquivosActionPerformed(evt);
            }
        });

        jtNumeroConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNumeroContaActionPerformed(evt);
            }
        });

        jtPrimeiroNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPrimeiroNomeActionPerformed(evt);
            }
        });

        jtBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtBalanceActionPerformed(evt);
            }
        });

        jtSobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtSobrenomeActionPerformed(evt);
            }
        });

        jLabel1.setText("Numero da Conta:");

        jLabel2.setText("Nome:");

        jLabel3.setText("Sobrenome:");

        jLabel4.setText("Balance:");

        jlEstadoArquivo.setText("Arquivo Não Aberto!");
        jlEstadoArquivo.setName("jlEstadoArquivo"); // NOI18N

        jbEnviarDados.setText("Enviar Dados");
        jbEnviarDados.setName("jbEnviarArquivos"); // NOI18N
        jbEnviarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEnviarDadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbAbrirArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addComponent(jlEstadoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jbFecharArquivos))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtPrimeiroNome, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtSobrenome)))
                            .addComponent(jtNumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbEnviarDados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbAbrirArquivo)
                        .addComponent(jbFecharArquivos))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlEstadoArquivo)))
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtNumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtPrimeiroNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addComponent(jtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jbEnviarDados)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAbrirArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAbrirArquivoActionPerformed
        if (arquivo.openFile()) {
            jlEstadoArquivo.setText("Arquivo Aberto!");
        }
        
    }//GEN-LAST:event_jbAbrirArquivoActionPerformed

    private void jtPrimeiroNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPrimeiroNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPrimeiroNomeActionPerformed

    private void jtNumeroContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNumeroContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNumeroContaActionPerformed

    private void jtBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtBalanceActionPerformed

    private void jbFecharArquivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFecharArquivosActionPerformed
        if (arquivo.closeFile() == 1) {
            jlEstadoArquivo.setText("Arquivo Fechado!");
        }
    }//GEN-LAST:event_jbFecharArquivosActionPerformed

    private void jbEnviarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEnviarDadosActionPerformed
        if (jlEstadoArquivo.getText().equals("Arquivo Aberto!") && !(jtNumeroConta.getText().equals("") ||
                jtPrimeiroNome.getText().equals("") ||
                jtSobrenome.getText().equals("") ||
                jtBalance.getText().equals("") )){
           
            int acc;
            String fname;
            String lname;
            int bal;
            int erro;
            
            acc = Integer.parseInt(jtNumeroConta.getText());
            fname = jtPrimeiroNome.getText();
            lname = jtSobrenome.getText();
            bal = Integer.parseInt(jtBalance.getText());
            
            erro = arquivo.addRecords(acc, fname, lname, bal);
            
            switch (erro) {
                
                case -1:
                    JOptionPane.showMessageDialog(rootPane, "O numero da conta nao pode ser negativo");
                    break;
                   
                case -2:
                    JOptionPane.showMessageDialog(rootPane, "Valores Invalidos");
                    break;
            
                case 1:
                    jtNumeroConta.setText("");
                    jtPrimeiroNome.setText("");
                    jtSobrenome.setText("");
                    jtBalance.setText("");
                    break;
            }
        }
    }//GEN-LAST:event_jbEnviarDadosActionPerformed

    private void jtSobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtSobrenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtSobrenomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbAbrirArquivo;
    private javax.swing.JButton jbEnviarDados;
    private javax.swing.JButton jbFecharArquivos;
    private javax.swing.JLabel jlEstadoArquivo;
    private javax.swing.JTextField jtBalance;
    private javax.swing.JTextField jtNumeroConta;
    private javax.swing.JTextField jtPrimeiroNome;
    private javax.swing.JTextField jtSobrenome;
    // End of variables declaration//GEN-END:variables
}
