/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.appfileserializado;

import com.mycompany.appfileserializado.InterfacesAlt.Escrever;
import com.mycompany.appfileserializado.InterfacesAlt.Ler;
import javax.swing.JOptionPane;

/**
 *
 * @author luizh
 */
public class InterfaceMain extends javax.swing.JFrame {
    /**
     * Creates new form InterfaceMain
     */
    public InterfaceMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMSair = new javax.swing.JMenu();
        jMExit = new javax.swing.JMenuItem();
        jMCriar = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMAdicionar = new javax.swing.JMenu();
        jMWrite = new javax.swing.JMenuItem();
        jMLer = new javax.swing.JMenu();
        jMRead = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        javax.swing.GroupLayout jDesktopLayout = new javax.swing.GroupLayout(jDesktop);
        jDesktop.setLayout(jDesktopLayout);
        jDesktopLayout.setHorizontalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopLayout.setVerticalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        jMSair.setText("Sair");
        jMSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSairActionPerformed(evt);
            }
        });

        jMExit.setText("Sair do Aplicativo");
        jMExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMExitActionPerformed(evt);
            }
        });
        jMSair.add(jMExit);

        jMenuBar1.add(jMSair);

        jMCriar.setText("Arquivo");
        jMCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCriarActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Criar novo Arquivo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMCriar.add(jMenuItem1);

        jMenuBar1.add(jMCriar);

        jMAdicionar.setText("Adicionar");

        jMWrite.setText("Adicionar Dados");
        jMWrite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMWriteActionPerformed(evt);
            }
        });
        jMAdicionar.add(jMWrite);

        jMenuBar1.add(jMAdicionar);

        jMLer.setText("Ler");

        jMRead.setText("Ler registros");
        jMRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMReadActionPerformed(evt);
            }
        });
        jMLer.add(jMRead);

        jMenuBar1.add(jMLer);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSairActionPerformed
        
    }//GEN-LAST:event_jMSairActionPerformed

    private void jMCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCriarActionPerformed
        
    }//GEN-LAST:event_jMCriarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CreateRandomFile file = new CreateRandomFile();
        
        switch (file.CreateFile()) {
            case 0:
                JOptionPane.showMessageDialog(rootPane, "Arquivo criado!");
                break;
                
            case 1:
                JOptionPane.showMessageDialog(rootPane, "Erro ao gravar o Arquivo!");
                break;
                
            case 2:
                JOptionPane.showMessageDialog(rootPane, "Erro ao processar o Arquivo!");
                break;
                
            case 3: 
                JOptionPane.showMessageDialog(rootPane, "Erro ao fechar o Arquivo!");
                break;
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMExitActionPerformed

    private void jMWriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMWriteActionPerformed
        Escrever form = new Escrever();
        jDesktop.add(form);
        form.show();
    }//GEN-LAST:event_jMWriteActionPerformed

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    private void jMReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMReadActionPerformed
        Ler form = new Ler();
        jDesktop.add(form);
        form.show();
    }//GEN-LAST:event_jMReadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new InterfaceMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktop;
    private javax.swing.JMenu jMAdicionar;
    private javax.swing.JMenu jMCriar;
    private javax.swing.JMenuItem jMExit;
    private javax.swing.JMenu jMLer;
    private javax.swing.JMenuItem jMRead;
    private javax.swing.JMenu jMSair;
    private javax.swing.JMenuItem jMWrite;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
