
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author luizh
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTValor1 = new javax.swing.JTextField();
        jTValor2 = new javax.swing.JTextField();
        jBCalcular = new javax.swing.JButton();
        jRSoma = new javax.swing.JRadioButton();
        jRSubtracao = new javax.swing.JRadioButton();
        jRDivisao = new javax.swing.JRadioButton();
        jRMultiplicacao = new javax.swing.JRadioButton();
        jLResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("teste calculadora aula");
        setName("principal"); // NOI18N
        setResizable(false);

        jLabel1.setText("Valor 1:");
        jLabel1.setName("jlValor1"); // NOI18N

        jLabel2.setText("Valor 2:");
        jLabel2.setName("jlValor2"); // NOI18N

        jTValor1.setName("jtValor1"); // NOI18N
        jTValor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTValor1ActionPerformed(evt);
            }
        });

        jTValor2.setName("jtValor2"); // NOI18N

        jBCalcular.setText("Calcular");
        jBCalcular.setName("jbCalcular"); // NOI18N
        jBCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCalcularActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRSoma);
        jRSoma.setSelected(true);
        jRSoma.setText("Soma");
        jRSoma.setName("jRSoma"); // NOI18N
        jRSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRSomaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRSubtracao);
        jRSubtracao.setText("Subtracao");
        jRSubtracao.setName("jRSubtracao"); // NOI18N
        jRSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRSubtracaoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRDivisao);
        jRDivisao.setText("Divisao");
        jRDivisao.setName("jRDivisao"); // NOI18N
        jRDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRDivisaoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRMultiplicacao);
        jRMultiplicacao.setText("Multiplicacao");
        jRMultiplicacao.setName("jRMultiplicacao"); // NOI18N

        jLResultado.setForeground(new java.awt.Color(0, 102, 102));
        jLResultado.setName("jLResultado"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(210, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jRSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRDivisao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRSubtracao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRMultiplicacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jBCalcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTValor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTValor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTValor1ActionPerformed

    private void jRSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRSomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRSomaActionPerformed

    private void jRDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRDivisaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRDivisaoActionPerformed

    private void jBCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCalcularActionPerformed
        // TODO add your handling code here:
        Calculador calc;
        
        if (jTValor1.getText().equals("") || jTValor2.getText().equals(""))
            JOptionPane.showMessageDialog(rootPane, "Digite o valor");
        else {
            
            Double a;
            Double b;
            Double resultado;
            
            a = Double.parseDouble(jTValor1.getText());
            b = Double.parseDouble(jTValor2.getText());
            
            if (jRSoma.isSelected()) {
                calc = new Soma(a,b);
                
            }
            else if (jRSubtracao.isSelected()) {
                calc = new Subtracao(a,b);
                
            }
            else if (jRMultiplicacao.isSelected()) {
                calc = new Multiplicacao(a,b);
                
            }
            else {
                calc = new Divisao(a,b);
                
            }
            
            resultado = calc.Calcular();
            jLResultado.setText("Resultado: "+resultado);
            //JOptionPane.showMessageDialog(rootPane, "Resultado: "+resultado);
        }
    }//GEN-LAST:event_jBCalcularActionPerformed

    private void jRSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRSubtracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRSubtracaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jBCalcular;
    private javax.swing.JLabel jLResultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRDivisao;
    private javax.swing.JRadioButton jRMultiplicacao;
    private javax.swing.JRadioButton jRSoma;
    private javax.swing.JRadioButton jRSubtracao;
    private javax.swing.JTextField jTValor1;
    private javax.swing.JTextField jTValor2;
    // End of variables declaration//GEN-END:variables
}
