/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.appfileserializado.InterfacesAlt;

import com.mycompany.appfileserializado.WriteRandomFile;
import javax.swing.JOptionPane;

/**
 *
 * @author luizh
 */
public class Escrever extends javax.swing.JInternalFrame {
    static Integer index = 0;
    
    
    /**
     * Creates new form Escrever
     */
    public Escrever() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTNumeroConta = new javax.swing.JTextField();
        jTNome = new javax.swing.JTextField();
        jTSobrenome = new javax.swing.JTextField();
        jTSaldo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTSobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTSobrenomeActionPerformed(evt);
            }
        });

        jTSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTSaldoActionPerformed(evt);
            }
        });

        jLabel1.setText("Numero da Conta");

        jLabel2.setText("Nome");

        jLabel3.setText("Sobrenome");

        jLabel4.setText("Saldo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTSaldo)
                                .addComponent(jTNumeroConta)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jTSobrenome, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jButton1)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTNumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        WriteRandomFile file = new WriteRandomFile();
        
        if (file.openFile() == false) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao abrir o arquivo!");
            System.exit(0);
        }
        
        String numero = jTNumeroConta.getText();
        String nome = jTNome.getText();
        String sobrenome = jTSobrenome.getText();
        String saldo = jTSaldo.getText();
        
        if (index == 99)
            JOptionPane.showMessageDialog(rootPane, "Limite alcançado de registros!");
        else {
       
            if (saldo.isEmpty() || nome.isEmpty() || sobrenome.isEmpty() || numero.isEmpty()) 
                JOptionPane.showMessageDialog(rootPane, "Dados Faltantes!");
        
            else {
                switch (file.writeFile(Integer.parseInt(numero), nome, sobrenome, Double.parseDouble(saldo))) {
                    case -1:
                        JOptionPane.showMessageDialog(rootPane, "O numero da conta deve ser entre 0 e 100!");
                        break;
                
                    case 0:
                        JOptionPane.showMessageDialog(rootPane, "Dados salvos!");
                        
                        index++;
                        jTNumeroConta.setText("");
                        jTNome.setText("");
                        jTSobrenome.setText("");
                        jTSaldo.setText("");
                        break;
                
                    case 1:
                        JOptionPane.showMessageDialog(rootPane, "Erro ao gravar dados!");
                        break;
                
                    case 2:
                        JOptionPane.showMessageDialog(rootPane, "Dados invalidos!");
                        break;
                }
        
            }
        }
        
        if (file.closeFile() == false) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao fechar o arquivo!");
            System.exit(0);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTSobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTSobrenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTSobrenomeActionPerformed

    private void jTSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTSaldoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTNome;
    private javax.swing.JTextField jTNumeroConta;
    private javax.swing.JTextField jTSaldo;
    private javax.swing.JTextField jTSobrenome;
    // End of variables declaration//GEN-END:variables
}
