/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.appmdi;

import com.mycompany.appmdi.formularios.CLT;
import com.mycompany.appmdi.formularios.Empregados;
import com.mycompany.appmdi.formularios.Horista;

/**
 *
 * @author luizh
 */
public class FormMain extends javax.swing.JFrame {

    static Empregado empregados[] = new Empregado[10];
    static Integer index = 0;

    public static Empregado[] getEmpregados() {
        return empregados;
    }

    public static void setEmpregados(Empregado[] empregados) {
        FormMain.empregados = empregados;
    }

    public static Integer getIndex() {
        return index;
    }

    public static void setIndex(Integer index) {
        FormMain.index = index;
    }
    
    /**
     * Creates new form FormMain
     */
    public FormMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmArquivo = new javax.swing.JMenu();
        jmSair = new javax.swing.JMenuItem();
        jmCadastrar = new javax.swing.JMenu();
        jmCLT = new javax.swing.JMenuItem();
        jmHorista = new javax.swing.JMenuItem();
        jmConsultar = new javax.swing.JMenu();
        jmConsultarEmpregados = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopLayout = new javax.swing.GroupLayout(jDesktop);
        jDesktop.setLayout(jDesktopLayout);
        jDesktopLayout.setHorizontalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );
        jDesktopLayout.setVerticalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        jmArquivo.setText("Arquivo");

        jmSair.setText("Sair");
        jmSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSairActionPerformed(evt);
            }
        });
        jmArquivo.add(jmSair);

        jMenuBar1.add(jmArquivo);

        jmCadastrar.setText("Cadastrar");

        jmCLT.setText("CLT");
        jmCLT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCLTActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmCLT);

        jmHorista.setText("Horista");
        jmHorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmHoristaActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmHorista);

        jMenuBar1.add(jmCadastrar);

        jmConsultar.setText("Consultar");

        jmConsultarEmpregados.setText("Consultar Empregados");
        jmConsultarEmpregados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConsultarEmpregadosActionPerformed(evt);
            }
        });
        jmConsultar.add(jmConsultarEmpregados);

        jMenuBar1.add(jmConsultar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSairActionPerformed
        System.exit(0);    
    }//GEN-LAST:event_jmSairActionPerformed

    private void jmCLTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCLTActionPerformed
        CLT form = new CLT();
        jDesktop.add(form);
        form.show();
        
    }//GEN-LAST:event_jmCLTActionPerformed

    private void jmHoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmHoristaActionPerformed
        Horista form = new Horista();
        jDesktop.add(form);
        form.show();
    
    }//GEN-LAST:event_jmHoristaActionPerformed

    private void jmConsultarEmpregadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConsultarEmpregadosActionPerformed
        Empregados form = new Empregados();
        jDesktop.add(form);
        form.show();
        
    }//GEN-LAST:event_jmConsultarEmpregadosActionPerformed
    
    public void inserirCLT (String nome, String endereco, String cpf, Double sBrutoCLT){
        EmpregadoCLT temp = new EmpregadoCLT(nome, endereco, cpf, sBrutoCLT);
        
        System.out.println("Nome: "+temp.getNome());
        System.out.println("Cpf: "+temp.getCpf());
        System.out.println("Endereco: "+temp.getEndereco());
        System.out.println("Salario Bruto: "+temp.getsBrutoCLT());
        System.out.println("Index: "+index);
        
        empregados[index++] = temp;
    }
    
    public void inserirHorista(String nome, String cpf, String endereco, int nHoras, Double precoH){
        EmpregadoHorista temp = new EmpregadoHorista(nome, cpf, endereco, nHoras, precoH);
        
        System.out.println("Nome: "+temp.getNome());
        System.out.println("Cpf: "+temp.getCpf());
        System.out.println("Endereco: "+temp.getEndereco());
        System.out.println("Numero de Horas: "+temp.getnHoras());
        System.out.println("Preco das Horas: "+temp.getPrecoH());
        System.out.println("Index: "+index);
        
        empregados[index++] = temp;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmArquivo;
    private javax.swing.JMenuItem jmCLT;
    private javax.swing.JMenu jmCadastrar;
    private javax.swing.JMenu jmConsultar;
    private javax.swing.JMenuItem jmConsultarEmpregados;
    private javax.swing.JMenuItem jmHorista;
    private javax.swing.JMenuItem jmSair;
    // End of variables declaration//GEN-END:variables
}
